In [90]:
import pandas as pd
import numpy as np

In [94]:
data = pd.read_csv('train_data.txt' , sep='delimiter', delimiter = "\t", header=None , index_col=False )
print(data)

                0      1
0              কী      O
1           কারণে      O
2          তাঁদের      O
3           মধ্যে      O
4          ঝামেলা      O
...           ...    ...
67549      রেখেছে      O
67550      আর্সেন  B-PER
67551  ওয়েঙ্গারের  I-PER
67552          দল      O
67553           ।      O

[67554 rows x 2 columns]

In [95]:
print(data.head(3))

        0  1
0      কী  O
1   কারণে  O
2  তাঁদের  O

In [103]:
data.columns =[ 'words' , 'labels']

In [104]:
data.head(20)

         words labels
0           কী      O
1        কারণে      O
2       তাঁদের      O
3        মধ্যে      O
4       ঝামেলা      O
5        হয়েছে      O
6            ,      O
7           তা      O
8         জানি      O
9         না।’      O
10       বরুড়া  B-LOC
11       থানার      O
12  ভারপ্রাপ্ত      O
13   কর্মকর্তা      O
14           (      O
15         ওসি      O
16           )      O
17           এ  B-PER
18          কে  B-PER
19          এম  B-PER

In [105]:
print(data)

            words labels
0              কী      O
1           কারণে      O
2          তাঁদের      O
3           মধ্যে      O
4          ঝামেলা      O
...           ...    ...
67549      রেখেছে      O
67550      আর্সেন  B-PER
67551  ওয়েঙ্গারের  I-PER
67552          দল      O
67553           ।      O

[67554 rows x 2 columns]

In [36]:
data = data.reset_index()

In [106]:
data.head(20)

         words labels
0           কী      O
1        কারণে      O
2       তাঁদের      O
3        মধ্যে      O
4       ঝামেলা      O
5        হয়েছে      O
6            ,      O
7           তা      O
8         জানি      O
9         না।’      O
10       বরুড়া  B-LOC
11       থানার      O
12  ভারপ্রাপ্ত      O
13   কর্মকর্তা      O
14           (      O
15         ওসি      O
16           )      O
17           এ  B-PER
18          কে  B-PER
19          এম  B-PER

In [107]:
data.count

<bound method DataFrame.count of             words labels
0              কী      O
1           কারণে      O
2          তাঁদের      O
3           মধ্যে      O
4          ঝামেলা      O
...           ...    ...
67549      রেখেছে      O
67550      আর্সেন  B-PER
67551  ওয়েঙ্গারের  I-PER
67552          দল      O
67553           ।      O

[67554 rows x 2 columns]>

In [108]:
data['sentence_id'] = (data['words'].str.contains('[।?!]')
                                .shift()
                                .bfill()
                                .cumsum()
                     )

In [109]:
data.head(50)

         words labels  sentence_id
0           কী      O            0
1        কারণে      O            0
2       তাঁদের      O            0
3        মধ্যে      O            0
4       ঝামেলা      O            0
5        হয়েছে      O            0
6            ,      O            0
7           তা      O            0
8         জানি      O            0
9         না।’      O            0
10       বরুড়া  B-LOC            1
11       থানার      O            1
12  ভারপ্রাপ্ত      O            1
13   কর্মকর্তা      O            1
14           (      O            1
15         ওসি      O            1
16           )      O            1
17           এ  B-PER            1
18          কে  B-PER            1
19          এম  B-PER            1
20      কাউছার  I-PER            1
21      চৌধুরী  I-PER            1
22        বলেন      O            1
23           ,      O            1
24        ‘ঝলম  B-LOC            1
25      ইউনিয়ন      O            1
26    যুবলীগের  I-ORG            1
27       কর্মী      O            1
28       মাসুম  I-PER            1
29   ছাত্রদলের  B-ORG            1
30       কর্মী      O            1
31   সাদ্দামকে  B-PER            1
32        গুলি      O            1
33        করেন      O            1
34           ।      O            1
35   আশঙ্কাজনক      O            2
36     অবস্থায়      O            2
37      উপজেলা  B-ORG            2
38   স্বাস্থ্য  I-ORG            2
39  কমপ্লেক্সে  I-ORG            2
40      নেওয়ার      O            2
41        পথেই      O            2
42        তাঁর      O            2
43      মৃত্যু      O            2
44          হয়      O            2
45           ।      O            2
46      খুলনার  B-LOC            3
47     দিঘলিয়া  B-LOC            3
48     উপজেলার      O            3
49    বারাকপুর  B-LOC            3

In [110]:
data = data[['sentence_id','words','labels']]

In [111]:
print(data)

       sentence_id       words labels
0                0          কী      O
1                0       কারণে      O
2                0      তাঁদের      O
3                0       মধ্যে      O
4                0      ঝামেলা      O
...            ...         ...    ...
67549         4920      রেখেছে      O
67550         4920      আর্সেন  B-PER
67551         4920  ওয়েঙ্গারের  I-PER
67552         4920          দল      O
67553         4920           ।      O

[67554 rows x 3 columns]

In [112]:
data.head(30)

    sentence_id       words labels
0             0          কী      O
1             0       কারণে      O
2             0      তাঁদের      O
3             0       মধ্যে      O
4             0      ঝামেলা      O
5             0       হয়েছে      O
6             0           ,      O
7             0          তা      O
8             0        জানি      O
9             0        না।’      O
10            1       বরুড়া  B-LOC
11            1       থানার      O
12            1  ভারপ্রাপ্ত      O
13            1   কর্মকর্তা      O
14            1           (      O
15            1         ওসি      O
16            1           )      O
17            1           এ  B-PER
18            1          কে  B-PER
19            1          এম  B-PER
20            1      কাউছার  I-PER
21            1      চৌধুরী  I-PER
22            1        বলেন      O
23            1           ,      O
24            1        ‘ঝলম  B-LOC
25            1      ইউনিয়ন      O
26            1    যুবলীগের  I-ORG
27            1       কর্মী      O
28            1       মাসুম  I-PER
29            1   ছাত্রদলের  B-ORG